# Generated by Django 3.1.1 on 2020-09-15 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vrp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.IntegerField()),
                ('routing_plan', models.TextField()),
                ('total_distance', models.IntegerField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vrp.vrpproblem')),
            ],
        ),
    ]
