# Generated by Django 3.1.1 on 2020-09-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrp', '0002_routingplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='vrpproblem',
            name='data_path',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
